services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: iotapp.settings
    command: >
      sh -c "python iotapp/manage.py makemigrations && 
             python iotapp/manage.py migrate && 
             python iotapp/manage.py runserver 0.0.0.0:8000"